version: "3.9"
services:
  test:
    image: python:3.11
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "8000:5000"
    # volumes:
    #   - .:/code
    # environment:
    #   FLASK_DEBUG: "true"
